new change

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -20,9 +20,20 @@ jobs:
         with:
           node-version: 20
 
-      - name: Print PR Number
+      - name: Print Event
         run: |
-          echo "PR Number = ${{ github.event.client_payload.pr_number }}"
+          echo "Event Name: ${{ github.event_name }}"
+          echo "PR Number: ${{ github.event.client_payload.pr_number }}"
+
+      - name: Verify PAT
+        env:
+          GH_TOKEN: ${{ secrets.PLAYWRIGHT_PAT }}
+        run: |
+          if [ -z "$GH_TOKEN" ]; then
+            echo "PLAYWRIGHT_PAT is missing!"
+            exit 1
+          fi
+          echo "PAT Loaded Successfully"
 
       - name: Get PR Details
         env:
@@ -31,10 +42,10 @@ jobs:
           curl \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer $GH_TOKEN" \
-            https://api.github.com/repos/j3-m2stack/angular_dashboard/pulls/${{ github.event.client_payload.pr_number }}
+            https://api.github.com/repos/j3-m2stack/angular_dashboard_1/pulls/${{ github.event.client_payload.pr_number }}
 
       - name: Install Dependencies
-        run: npm install
+        run: npm ci
 
       - name: Install Playwright Browsers
         run: npx playwright install --with-deps
